language: go

go:
  - 1.11.x

before_install:
  # We're making an assumption here that pulling these images in order to use
  # their layers for cache is faster than installing dependencies for every build.
  - docker pull containership/cloud-agent:latest
  - docker pull containership/cloud-agent:builder
  - docker pull containership/cloud-coordinator:latest
  - docker pull containership/cloud-coordinator:builder

install:
  - glide install -v

jobs:
  include:
    - stage: "Tests"
      name: "Format Check"
      script: make fmt-check
    - script: make vet
      name: "Vet"
    - script: make lint
      name: "Lint"
    - script: make verify
      name: "Verify Generated Code"
    - script: make coverage
      name: "Unit Test and Coverage"

    - stage: "Build"
      name: "Build Agent"
      script: make build-agent
    - script: make build-coordinator
      name: "Build Coordinator"

after_success:
  - bash <(curl -s https://codecov.io/bash)
