sudo: required

language: go

services:
  - docker

go:
  - 1.11.x

before_install:
  # We're making an assumption here that pulling these images in order to use
  # their layers for cache is faster than installing dependencies for every build.
  - docker pull containership/cloud-agent:latest
  - docker pull containership/cloud-agent:builder
  - docker pull containership/cloud-coordinator:latest
  - docker pull containership/cloud-coordinator:builder

install:
  - make build-test

jobs:
  include:
    - stage: "Test"
      name: "Format Check"
      script: docker run -it containership/cluster-manager-test make fmt-check
    - script: docker run -it containership/cluster-manager-test make vet
      name: "Vet"
    - script: docker run -it containership/cluster-manager-test make lint
      name: "Lint"
    - script: docker run -it containership/cluster-manager-test make verify
      name: "Verify Generated Code"
    - script:
      - mkdir shared
      - docker run -v "$PWD/shared:/shared" -it containership/cluster-manager-test bash -c "make coverage && mv coverage.txt /shared"
      name: "Unit Test and Coverage"

    - stage: "Build"
      name: "Build Agent and Coordinator"
      script: make build-agent
      script: make build-coordinator

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push containership/cloud-agent:latest
    - docker push containership/cloud-coordinator:latest
