apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: authorizationroles.auth.containership.io
  labels:
    containership.io/managed: "true"
spec:
  group: auth.containership.io
  version: v3
  scope: Namespaced
  names:
    kind: AuthorizationRole
    plural: authorizationroles
    shortNames:
      - authrole
